### PR TITLE
Implement logic to remove a person's role when all of their bots leav…

### PR DESCRIPTION
**Pull request by Hadock-is-ok**
…e the server.

TAKE 2 💀

### CODE REVIEW

**Comment by Hadock-is-ok** [comment]
cc: @LeoCx1000

**Review by LeoCx1000 — APPROVED** [review]
Lgtm.

**Comment by crygup** [comment]
wgtm

**Comment by Hadock-is-ok** [comment]
> wgtm

What's wgtm?

**Comment by LeoCx1000** [comment]
Wooks good to mwe, obviously

**Pull request merged**
